app/modules/sms/controllers/DefaultController.php
<?php

class DefaultController extends SmsModuleController {

    public function init() {
        $this->resource = UserResources::RES_MESSAGING;
        $this->activeMenu = self::MENU_QUICK;
        $this->showPageTitle = false;
        parent::init();
    }

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('Quick', 'custome', 'file2sms', 'inbox', 'insert', 'logss', 'verify', 'smspreview', 'approval', 'view', 'phonebook', 'add', 'contacts', 'logs', 'update', 'customedit', 'addsig', 'approve' , 'delete' , 'download'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    
    
        /**
         * Deletes a particular model.
         * If deletion is successful, the browser will be redirected to the 'admin' page.
         * @param integer $id the ID of the model to be deleted
         */
        public function actionDelete($id)
        {
                $model = Contacts::model()->loadModel($id);
                $this->checkPrivilege($model, Acl::ACTION_DELETE);

                $model->delete();

                if (!isset($_GET['ajax']))
                        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }

    /**
     * The Quick SMS sending function.
     * @return array access control rules
     */
    public function actionAddsig() {
        $id = $_POST['value'];
        $val = Signatures::model()->getScaler("body", "id = $id");
        echo "\n" . $val;
    }

    public function actionQuick($id = null, $_nt = null) {
        $this->hasPrivilege(Acl::ACTION_CREATE);
        $this->activeMenu = self::MENU_QUICK;
        $this->resourceLabel = 'Quick SMS';
        $this->activeTab = 0;
        $this->pageTitle = Lang::t('Send ' . $this->resourceLabel);
        if($_nt):
           $notify = Notification::model()->loadModel($_nt);
           $notify->Status = "Read";
           $notify->save(FALSE);
        endif;
         $model = (null === $id) ? new Sms() : Sms::model()->loadModel($id);
        $model_class_name = $model->getClassName();
        
        if (isset($_POST[$model_class_name])) {
            $model->attributes = $_POST[$model_class_name];
            $model->Time = $_POST['Time'];
            $model->Batch = strtoupper(time());
            $model->Status = Sms::STATUS_PENDING;
            $model->Sender_account = Yii::app()->user->account;
            $model->SmsType = Sms::QUICKSMS;
            if ($model->save())
           
                Yii::app()->user->setFlash('success', Lang::t('SMS Submitted successfully for peer reviewal'));
            $this->redirect(array('view', 'id' => $model->SmsID, 'type' => 0));
        }

        $this->render('create', array(
            'model' => $model,
            'id' => $id,
            '_nt' => $_nt
        ));
    }

    /*
     * Customized SMS module. All phone book are saved in the database
     * 
     * 
     */

    public function actionCustome($id = null, $_nt = false) {
        
        $this->hasPrivilege(Acl::ACTION_CREATE);
        $this->activeMenu = self::MENU_CUSTOME;
        $this->resourceLabel = 'Customized SMS';
        $this->activeTab = 1;
        $this->pageTitle = Lang::t('Send ' . $this->resourceLabel);
        if($_nt):
           $notify = Notification::model()->loadModel($_nt);
           $notify->Status = "Read";
           $notify->save(FALSE);
        endif;
        $model = (null === $id) ? new Sms() : Sms::model()->loadModel($id);
        $model_class_name = $model->getClassName();

        if (isset($_POST[$model_class_name])) {
            $model->attributes = $_POST[$model_class_name];
            $model->Time = $_POST['Time'];
            $model->validate();
            $model->Recepient = implode(',', $model->Recepient);
            $model->Batch = strtoupper(time());
            $model->Status = Sms::STATUS_PENDING;
            $model->SmsType = Sms::CUSTOMESMS;
            if ($model->save())
                Yii::app()->user->setFlash('success', Lang::t('SMS Submitted successfully for reviewal'));
            $this->redirect(array('view', 'id' => $model->SmsID, 'type' => 1));
        }
        $this->render('custome', array(
            'model' => $model,
            'id' => $id,
            '_nt' => $_nt
        ));
    }
    
    public function actionVerify() {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->activeTab = 4;
        $this->activeMenu = self::MENU_VERIFY;
        $this->showPageTitle = false;
        $searchModel = Sms::model()->searchModel(array(), $this->settings[Constants::KEY_PAGINATION], 'Datetime DESC', "Status = '" . Sms::STATUS_PENDING . "' AND Sender_account = " . Yii::app()->user->account . " GROUP BY Batch");
        $this->render('verify', array(
            'model' => $searchModel,
        ));
    }

    public function actionFile2sms($id = null, $_nt = false , $_st = 1) {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->activeMenu = self::MENU_FILE2SMS;
        $this->activeTab = 2;
        $this->pageTitle = "File2SMS";
        $this->showPageTitle = false;
        $model = new Phonebook;
        $aData = array();
        $data = array();
                    
        $model_class_name = $model->getClassName();
        if (isset($_POST[$model_class_name])) {
            
            $model->attributes = $_POST[$model_class_name];
            $model->validate();
              $mimes = array('application/vnd.ms-excel', 'text/plain', 'text/csv', 'text/tsv');
            if (!empty($_FILES[$model_class_name]['tmp_name']['csv_file']) AND in_array($_FILES[$model_class_name]['type']['csv_file'], $mimes)) {
            $_st = 2;
               // Read all the rows and columns
            $file = CUploadedFile::getInstance($model, 'csv_file');
                
                $fp = fopen($file->tempName, 'r');

                if ($fp) {
                    
                    //$filesize = filesize($file);
                    $firstRow = true;
                    while (($data = fgetcsv($fp, 65536, ",")) !== false) {
                        if($firstRow) {
                            $aData['titles'] = $data;
                            $firstRow = false;
                        } else {
                                 array_push($aData, $data);
                           
                        }
                    }
                    fclose($fp);
                    
                }
                                }
            else {
                $model->addError('csv_file', 'Please Upload a Valid CSV file');
            }
        }
        if(isset($_POST['to_second'])){
            $_st = 2;
            $model = new Sms;
            $aData = unserialize($_POST['csv_file']);
        }
        if(isset($_POST['to_third'])){
            $_st = 3;
            $model = new Sms;
            $aData = unserialize($_POST['csv_file']);
        }
        if($_nt AND !isset($_POST["Sms"])){
            $_st = 3;
            $notify = Notification::model()->loadModel($_nt);
            $notify->Status = "Read";
            $notify->save(FALSE);
            $model = ($_nt != false) ? Sms::model()->loadModel($id) : new Sms;
            $aData = unserialize(File2sms::model()->getScaler("Data" ,  "Smsid= $id"));
        }
        if(isset($_POST['to_last'])){
            $_st = 4;
            $model = ($_nt != false) ? Sms::model()->loadModel($id) : new Sms;
            $model_class_name = $model->getClassName();
            $model->attributes = $_POST[$model_class_name];
            $aData = unserialize($_POST['csv_file']);
        }
       if (isset($_POST["to_save"])) {
              $model = ($_nt != false) ? Sms::model()->loadModel($id) : new Sms;
              $model_class_name = $model->getClassName();
               $save = new File2sms;
               $model->attributes = $_POST[$model_class_name];
               $model->SmsType = Sms::FILE2SMS;
               $model->SenderID =  Sender::model()->get(Accounts::model()->get(Yii::app()->user->account , "Sender_id"));
               $model->Status = Sms::STATUS_PENDING;
               $model->Batch = strtoupper(time());
               $model->save(false);
               $save->Smsid = $model->SmsID;
               $save->Data = $_POST['csv_file'];
               $save->Status = File2sms::STATUS_PENDING;
               if($save->save(false))
                 $_st = 5;
                        
          }
           
        
        $this->render('file2sms', array(
            'st' => $_st,
            'model' => $model,
            'aData' => $aData,
        ));
    }
    
    protected function kaziNgumuSana($sms , $data , $key) {
        preg_match_all('/{(.*?)}/', $sms, $out);
        $id = 0;
        
       foreach($out[0] As $param):
           $name = array_search(substr($param,1,-1), $data['titles']);
           $sms = str_replace($param, $data[$key][$name], $sms);
                     
           $id++;
           
        endforeach;
        echo $sms;
        
    }
    public function actionInbox() {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->activeMenu = self::MENU_INBOX;
        $this->activeTab = 3;
        $this->pageTitle = "Sms Inbox";
        $this->showPageTitle = false;
        $model=new Incoming();
        $criteria=new CDbCriteria;
        $criteria->order = 'status ASC, time DESC';
        $total = $model->count($criteria);

app/modules/sms/controllers/VerifyController.php
<?php

class VerifyController extends SmsModuleController {

    public function init() {
        $this->resource = UserResources::RES_SMS_E_VERIFY;
        $this->activeMenu = self::MENU_E_VERIFY;
        $this->showPageTitle = false;
        parent::init();
    }

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete',
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow',
                'actions' => array('index', 'accounts' , 'create' , 'update' , 'delete' , 'logs','successful','failed','tabidsession','smslogs'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    
    public function actionIndex() {
        
       $this->resource = UserResources::RES_SMS_E_VERIFY;
       $this->hasPrivilege(Acl::ACTION_VIEW);
       $this->activeTab = 1;
        $this->PageTitle = "Manage E verify Accounts";
        $this->activeMenu = self::MENU_E_VERIFY;
        $this->showPageTitle = false;
       
       $this->render('everify', array('model' => Eaccounts::model()->searchModel(array(), $this->settings[Constants::KEY_PAGINATION], 'account_name'),));
   
    }
    
    /**
         * Creates a new model.
         * If creation is successful, the browser will be redirected to the 'view' page.
         */
        public function actionCreate()
        {
                $this->hasPrivilege(Acl::ACTION_CREATE);
                 $this->resourceLabel = "E-verify account";
                 $this->pageTitle = Lang::t('Add ' . $this->resourceLabel);

                $model = new Eaccounts();
                $model_class_name = $model->getClassName();

                if (isset($_POST[$model_class_name])) {
                   
                        $model->attributes = $_POST[$model_class_name];
                         if ($model->save()) {
                                Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                                $this->redirect(array('index'));
                        }
 
                }

                $this->render('create', array(
                    'model' => $model,
                ));
        }

        /**
         * Updates a particular model.
         * If update is successful, the browser will be redirected to the 'view' page.
         * @param integer $id the ID of the model to be updated
         */
        public function actionUpdate($id)
        {
                $this->hasPrivilege(Acl::ACTION_UPDATE);
                $this->resourceLabel = "E-verify account";
                $this->pageTitle = Lang::t('Edit ' . $this->resourceLabel);


                $model = Eaccounts::model()->loadModel($id);
                $model_class_name = $model->getClassName();

                if (isset($_POST[$model_class_name])) {
                        $model->attributes = $_POST[$model_class_name];
                        if ($model->save()) {
                                Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                                $this->redirect(array('index'));
                        }
                }

                $this->render('update', array(
                    'model' => $model,
                ));
        }
		
/////tad sesion id
	public function actionSmslogs(){
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->activeTab = 0;
        $this->activeMenu = self::MENU_LOGS;
        $this->pageTitle = "View Sms Logs and Status";
        $this->showPageTitle = false;
	$searchModel = Smslogsarchive::model()->searchModel(array(), $this->settings[Constants::KEY_PAGINATION], 'Datetime DESC' , " SenderID !=2 ");
        $this->render('logs', array(
            'model' => $searchModel,
        ));	
    }


		//faide smses
		 public function actionFailed(){
			 
	     $this->hasPrivilege(Acl::ACTION_VIEW);
             $this->activeTab = 2;
             $this->activeMenu = self::MENU_LOGS;
             $this->pageTitle = "Failed Logs";
             $this->showPageTitle = false;
			 $model= Smslogs::model()->searchModel(array(), $this->settings[Constants::KEY_PAGINATION], 'Datetime Desc', "Status NOT LIKE 'Success' AND Status NOT LIKE 'Pending' AND SenderID !=2 ");
			 // var_dump($model);die;
			  $this->render('failed', array(
                    'model' => $model,
                ));
			}
		//Lists all successfull logs
		 public function actionSuccessful(){
			 
	     $this->hasPrivilege(Acl::ACTION_VIEW);
             $this->activeTab = 1;
             $this->activeMenu = self::MENU_LOGS;
             $this->pageTitle = "Successful Logs";
             $this->showPageTitle = false;
	     $model= Smslogsarchive::model()->searchModel(array(), $this->settings[Constants::KEY_PAGINATION], 'Datetime Desc', "Status LIKE 'Success' AND SenderID !=2 ");
			 // var_dump($model);die;
	     $this->render('success', array(
                    'model' => $model,
                ));
				
			}

        /**
         * Deletes a particular model.
         * If deletion is successful, the browser will be redirected to the 'admin' page.
         * @param integer $id the ID of the model to be deleted
         */
        public function actionDelete($id)
        {
                Acl::hasPrivilege($this->privileges, $this->resource, Acl::ACTION_DELETE);
                Signatures::model()->loadModel($id)->delete();
                if (!isset($_GET['ajax']))
                        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
       
        public function actionLogs() {
        $this->hasPrivilege(Acl::ACTION_VIEW);
        $this->activeTab = 1;
        $this->activeMenu = self::MENU_LOGS;
        $this->pageTitle = "View Sms Logs and Status";
        $this->showPageTitle = false;
        
    }
	
}

app/modules/sms/views/default/_form.php
<?php

$form = $this->beginWidget('CActiveForm', array(
    'id' => 'quick-sms-form',
    'enableAjaxValidation' => false,
    'htmlOptions' => array(
        'class' => 'form-horizontal',
        'role' => 'form',
    )
        ));
?>


<?php
 if($_nt):
            
        $comment = Notification::model()->get($_nt , "Message");
        $user = UsersView::model()->get(Notification::model()->get($_nt , "User_account") , "name");
          echo "<div class=\"alert alert-block alert-danger clearfix\">
                        <button type=\"button\" class=\"close\" data-dismiss=\"alert\"><i class=\"icon-remove\"></i></button>
                        <div><span class='text-muted Italic'>Reviewed by $user:</span>   '$comment'</div>
                </div>" ; 
           
        endif; 
        ?>
<div class="form-group">
                <?php echo $form->labelEx($model, 'Recepient', array('class' => 'col-lg-3 control-label')); ?>
    <small class="text-muted">Enter phone numbers separated by comma</small>
                <div class="col-lg-5">
             <?php
            echo $form->textArea($model, 'Recepient', array('class' => "form-control" , "cols"=>"50" , 'rows' => '2' ,'required'=> true));
             ?>
                        
            <?php echo CHtml::error($model, 'Recepient') ?>
                </div>
        </div>
<div class="form-group">
                <?php echo $form->labelEx($model, 'SenderID', array('class' => 'col-lg-3 control-label')); ?>
                <div class="col-lg-5">
             <?php echo $form->textField($model, 'SenderID', array('class' => "form-control" , "value" => Sender::model()->get(Accounts::model()->get(Yii::app()->user->account , "Sender_id"), "SenderID"), 'readonly' => true));
              ?>
                        
            <?php echo CHtml::error($model, 'SenderID') ?>
                </div>
 </div>
<div class="form-group">
                <?php echo $form->labelEx($model, 'Schedule', array('class' => 'col-lg-3 control-label')); ?>
                <div class="col-lg-5">
             <?php echo $form->textField($model, 'Schedule', array('class' => "form-control " , 'id'=> 'datepicker' , 'value' => date('Y-m-d')));
              ?>
                        
            <?php echo CHtml::error($model, 'Schedule') ?>
                </div>
 </div>
<div class="form-group">
                <?php echo $form->labelEx($model, 'Time', array('class' => 'col-lg-3 control-label')); ?>
                <div class="col-lg-5">
            <?php echo  CHtml::textField('Time', date('h:i'), array('class'=>'timepicker',  'style' => 'width:150px')); ?>
                       
            <?php echo CHtml::error($model, 'Time') ?>
                </div>
 </div>
<div class="form-group">
        <?php echo $form->labelEx($model, 'Body', array('class' => 'col-lg-3 control-label')); ?>
    <small class="text-muted"  id="charNum">You have 160 characters left
</small>
        <div class="col-lg-5">
            <?php echo CHtml::error($model, 'Body') ?>
                <?php echo $form->textArea($model, 'Body', array('class' => 'form-control ', 'rows' => 6 , 'cols'=>50, "onkeyup"=>"countChar(this)" , 'id'=> 'body','required'=> true)); ?>
            </div>
</div>
<div class="form-group">
        <?php echo $form->labelEx($model, 'Signature', array('class' => 'col-lg-3 control-label')); ?>
    
        <div class="col-lg-5">
            <?php echo CHtml::error($model, 'Signature') ?>
                <?php
                    $datas = Signatures::model()->findAll();
                    $sigs = array();

                    foreach ($datas as $ds)
                        $sigs[$ds->id] = $ds->name;

                    echo $form->dropDownList($model, 'Signature', $sigs, array('prompt' => '[No Footer]',  'class' => 'forn-control chosen-select', 'id' => "signature"
                        ));
                    ?>
            <span id="loading"></span>
            </div>
</div>

        
             
  
<div class="clearfix form-actions">
        <div class="col-lg-offset-2 col-lg-9">
                <button class="btn btn-primary" type="submit"><i class="icon-ok bigger-110"></i> <?php echo Lang::t('submit for peer review') ?></button>
                &nbsp; &nbsp; &nbsp;
                <a class="btn" href="<?php echo $this->createUrl('manage') ?>"><i class="icon-remove bigger-110"></i><?php echo Lang::t('Cancel') ?></a>
        </div>
</div>
<?php $this->endWidget(); ?>


    <script>
      function countChar(val) {
        var len = val.value.length;
        if (len >= 161) {
          val.value = val.value.substring(0, 160);
        } else {
          $('#charNum').html('You have ' + (160 - len) + ' characters left');
        }
      };
      
      
      $('#signature').on('change', function (e) {
        e.preventDefault();
        var num = $(this).val();
        var optionSelected = "value=" + num;
        $('#loading').html("<img src= '<?php echo Yii::app()->request->baseUrl ?>/themes/default/images/ajax-loader.gif '/>");
        $.ajax
                ({
                    type: "POST",
                    url: "addsig",
                    data: optionSelected,
                    cache: false,
                    success: function(html)
                    {
                        $("#body").val($("#body").val() + html);
                         $('#loading').html("");
                    }
                });

    });
    </script>
    
    

<?php
Yii::app()->clientScript
        ->registerCssFile(Yii::app()->theme->baseUrl . '/plugins/chosen/chosen.min.css')
        ->registerScriptFile(Yii::app()->theme->baseUrl . '/plugins/chosen/chosen.jquery.min.js', CClientScript::POS_END)
        ->registerScript('recepient_id', "$('.chosen-select').chosen();");
?>
    

app/modules/sms/views/default/_grid.php
<?php

$grid_id = 'quick-sms-grid';
$this->widget('ext.MyGridView.ShowGrid', array(
    'title' => Lang::t($this->pageTitle),
    'titleIcon' => null,
    'showExportButton' => false,
    'showSearch' => true,
    'createButton' => array('visible'=> false),
    'showRefreshButton' => false,
    'grid' => array(
        'id' => $grid_id,
        'model' => $model,
        
        'columns' => array(
        array(
            'name' => "User_account",
            'type' => 'raw',
            'value' => 'UsersView::model()->get($data->User_account , "name")',
        ),
        array(
            'name' => "Peer_reviewer",
            'type' => 'raw',
            'value' => 'UsersView::model()->get($data->Peer_reviewer , "name")',
        ),
         
        array(
            'name' => "Approver",
            'type' => 'raw',
            'visible' => Yii::app()->controller->action->id == "logs" ? true : false,
            'value' => 'UsersView::model()->get($data->Peer_reviewer , "name")',
        ),
         
       
        
        array(
            'name' => 'Body',
            'type' => 'raw',
            'value' => '$data->Body',
        ),
           
        array(
            'name' => 'Status',
            'type' => 'raw',
            'value' => 'CHtml::tag(\'span\', array(\'class\' => "badge $data->class"), $data->Status)',
        ),
       
        array(
            'class' => 'ButtonColumn',
            'template' => ' {preview}&nbsp;&nbsp; {custome}&nbsp;&nbsp;{amend}&nbsp;&nbsp;{approve}',
            'htmlOptions' => array('class' => 'text-left', 'style' => 'width: 100px; text-align: left !important;'),
            'buttons' => array(
                
                
             
                
                'custome' => array(
                    'imageUrl' => false,
                    'label' => '<i class="icon-edit bigger-130"></i>',
                    'url' => 'Yii::app()->controller->createUrl("custome",array("id"=>$data->primaryKey))',
                    'visible' => '$this->grid->owner->showLink("' . UserResources::RES_QUICK_MESSAGING . '", "' . Acl::ACTION_UPDATE . '") AND ($data->Status == "' .Sms::STATUS_PENDING. '" OR $data->Status == "' .Sms::STATUS_RETURNED. '") AND $data->SmsType == "'. Sms::CUSTOMESMS .'" ?true:false',
                    'options' => array(
                        'class' => 'blue',
                        'title' => 'Amend custome SMS',
                    ),
                ),
                
                   
                'amend' => array(
                    'imageUrl' => false,
                    'label' => '<i class="icon-pencil bigger-130"></i>',
                    'url' => 'Yii::app()->controller->createUrl("quick",array("id"=>$data->primaryKey, "act"=>"edit", "asDialog"=>1,"gridId"=>$this->grid->id))',
                    
                    'visible' => '$this->grid->owner->showLink("' . UserResources::RES_QUICK_MESSAGING . '", "' . Acl::ACTION_UPDATE . '") AND ($data->Status == "' .Sms::STATUS_PENDING. '" OR $data->Status == "' .Sms::STATUS_RETURNED. '") AND $data->SmsType == "' .Sms::QUICKSMS. '" ?true:false',
                    'options' => array(
                        'class' => 'blue',
                        'title' => 'Amend SMS',
                    ),
                ),
                
                
                 'preview' => array(
                    'imageUrl' => false,
                    'label' => '<i class="icon-eye-open bigger-130"></i>',
                    'url' => 'Yii::app()->controller->createUrl("smspreview",array("id"=>$data->primaryKey,"asDialog"=>1,"gridId"=>$this->grid->id))',
                    'click'=>'function(){$("#previewframe").attr("src",$(this).attr("href")); $("#previewDialogue").dialog("open");  return false;}',
                    'visible' => '$this->grid->owner->showLink("' . UserResources::RES_SMS_APPROVALS . '", "' . Acl::ACTION_VIEW . '") ',
                    'options' => array(
                        'class' => 'brown show-colorbox',
                        'title' => 'preview SMSes',
                    ),
                ),
                
                'approve' => array(
                    'imageUrl' => false,
                    'label' => '<i class="icon-check bigger-130"></i>',
                    'url' => 'Yii::app()->controller->createUrl("approve",array("id"=>$data->primaryKey,"asDialog"=>1,"gridId"=>$this->grid->id))',
                    //'click'=>'function(){$("#approve-frame").attr("src",$(this).attr("href")); $("#approveDialogue").dialog("open");  return false;}',
                    'visible' => '$this->grid->owner->showLink("' . UserResources::RES_SMS_APPROVALS . '", "' . Acl::ACTION_VIEW . '") AND $data->Status == "' .Sms::STATUS_REVIEWED. '"?true:false',
                    'options' => array(
                        'class' => 'green show-colorbox',
                        'title' => 'Approve SMS',
                    ),
                ),
            )
        ),
    ),
)
)
)
;
?>


<?php
// Diaogue for adding new custom report
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(// the dialog
    'id' => 'updateDialogue',
    'options' => array(
        'title' => 'Amend SMS ',
        'autoOpen' => false,
        'modal' => false,
        'width' => 500,
        'height' => 400,
    ),
));
?>
<iframe id="update-frame" width="100%" height="100%"></iframe>
<?php $this->endWidget(); ?>



<?php
// Diaogue for approving SMS
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(// the dialog
    'id' => 'approveDialogue',
    'options' => array(
        'title' => 'Approve SMS ',
        'autoOpen' => false,
        'modal' => false,
        'width' => 500,
        'height' => 400,
    ),
));
?>
<iframe id="approve-frame" width="100%" height="100%"></iframe>
<?php $this->endWidget(); ?>


<?php
// Diaogue for adding new custom report
$this->beginWidget('zii.widgets.jui.CJuiDialog', array(// the dialog
    'id' => 'previewDialogue',
    'options' => array(
        'title' => 'Preview SMS',
        'autoOpen' => false,
        'modal' => true,
        'width' => 900,
        'height' => 500,
    ),
));
?>
<iframe id="previewframe" width="100%" height="100%">
 
</iframe>
<?php $this->endWidget(); ?>

app/modules/sms/views/default/_tab2.php
<div class="widget-toolbar no-border" style="float:left !important;">
    <ul class="nav nav-tabs my-nav">
       <li class="<?php echo $this->activeTab === 0 ? 'active' : '' ?>"><a href="<?php echo Yii::app()->createUrl(ModulesEnabled::MOD_MESSAGING.'/verify/smslogs') ?>"><i class="icon-envelope"></i> <?php echo Lang::t('All sms logs') ?></a></li>
       <li class="<?php echo $this->activeTab === 1 ? 'active' : '' ?>"><a href="<?php echo Yii::app()->createUrl(ModulesEnabled::MOD_MESSAGING.'/verify/successful') ?>"><i class="icon-check-sign"></i> <?php echo Lang::t('successful deliveries') ?></a></li>
       <li class="<?php echo $this->activeTab === 2 ? 'active' : '' ?>"><a href="<?php echo Yii::app()->createUrl(ModulesEnabled::MOD_MESSAGING.'/verify/failed') ?>"><i class="icon-exclamation-sign"></i> <?php echo Lang::t('failed sms logs') ?></a></li>
          
    </ul>
</div>

app/modules/sms/views/default/annually.php
<?php
/* @var $this SynchOrderController */

$this->breadcrumbs=array(
	'Synch Order'=>array('/synchOrder'),
	'Annually',
);
?>
<h1><?php echo $this->id . '/' . $this->action->id; ?></h1>

<p>
	You may change the content of this page by modifying
	the file <tt><?php echo __FILE__; ?></tt>.
</p>