app/modules/customization/controllers/DefaultController.php
<?php

/**
 * Settings default controller
 * @author James Makau <jacjimus@gmail.com>
 */
class DefaultController extends CustomizationModuleController {

        public function init()
        {
                parent::init();
                $this->resourceLabel = Lang::t('Settings Module');
                $this->resource = UserResources::RES_SETTINGS_GENERAL;
                $this->activeMenu = self::MENU_SETTINGS_GENERAL;
                $this->showPageTitle = false;
        }

        /**
         * @return array action filters
         */
        public function filters()
        {
                return array(
                    'accessControl', // perform access control for CRUD operations
                );
        }

        /**
         * Specifies the access control rules.
         * This method is used by the 'accessControl' filter.
         * @return array access control rules
         */
        public function accessRules()
        {
                return array(
                    array('allow',
                        'actions' => array('index', 'runtime', 'update', 'sms', 'create', 'delete' , 'activate' , 'signatures'),
                        'users' => array('@'),
                    ),
                    array('deny', // deny all users
                        'users' => array('*'),
                    ),
                );
        }

        public function actionIndex()
        {
                $this->resource = UserResources::RES_SETTINGS_GENERAL;
                $this->hasPrivilege(Acl::ACTION_VIEW);
                $this->showPageTitle = TRUE;
                $this->pageTitle = "Main Account Configuration";
                $this->activeMenu = self::MENU_SETTINGS_GENERAL;
                $accounts = new Accounts();
                if (isset($_POST['settings'])) {
                        $this->hasPrivilege(Acl::ACTION_UPDATE);

                        foreach ($_POST['settings'] as $key => $value) {
                                if (!empty($value)):
                                    if($key == Constants::KEY_LOGO){
                                       $value =  $accounts->setProfileImage($value , false);
                                   }
                                   Yii::app()->settings->set(Constants::CATEGORY_GENERAL, $key, $value);
                        
                                endif;
                        }
                       Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                        $this->refresh();
                }

                $settings = Yii::app()->settings->get(Constants::CATEGORY_GENERAL, array(
                    Constants::KEY_ADMIN_EMAIL,
                    Constants::KEY_COMPANY_NAME,
                    Constants::KEY_COMPANY_EMAIL,
                    Constants::KEY_CURRENCY,
                    Constants::KEY_PAGINATION,
                    Constants::KEY_SITE_NAME,
                    Constants::KEY_MIN_SMS_THREASHHOLD,
                    Constants::KEY_VENDOR_EMAIL,
                    Constants::KEY_MAIN_ACC_BALANCE,
                    Constants::KEY_DEFAULT_TIMEZONE,
                    Constants::KEY_LOGO,
                ));
               $this->render('index', array(
                    'settings' => $settings,
                ));
        }
/**
         * Creates a new model.
         * If creation is successful, the browser will be redirected to the 'view' page.
         */
        public function actionCreate()
        {
                $this->hasPrivilege(Acl::ACTION_CREATE);
                 $this->resourceLabel = "Sms Signatures";
                 $this->pageTitle = Lang::t('Add ' . $this->resourceLabel);

                $model = new Signatures;
                $model_class_name = $model->getClassName();

                if (isset($_POST[$model_class_name])) {
                   
                        $model->attributes = $_POST[$model_class_name];
                         if ($model->save()) {
                                Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                                $this->redirect(array('sms'));
                        }
 
                }

                $this->render('create', array(
                    'model' => $model,
                ));
        }

        /**
         * Updates a particular model.
         * If update is successful, the browser will be redirected to the 'view' page.
         * @param integer $id the ID of the model to be updated
         */
        public function actionUpdate($id)
        {
                $this->hasPrivilege(Acl::ACTION_UPDATE);
                $this->resourceLabel = "Notification template";
                $this->pageTitle = Lang::t('Edit ' . $this->resourceLabel);


                $model = Signatures::model()->loadModel($id);
                $model_class_name = $model->getClassName();

                if (isset($_POST[$model_class_name])) {
                        $model->attributes = $_POST[$model_class_name];
                        if ($model->save()) {
                                Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                                $this->redirect(array('signatures'));
                        }
                }

                $this->render('update', array(
                    'model' => $model,
                ));
        }

        /**
         * Deletes a particular model.
         * If deletion is successful, the browser will be redirected to the 'admin' page.
         * @param integer $id the ID of the model to be deleted
         */
        public function actionDelete($id)
        {
                Acl::hasPrivilege($this->privileges, $this->resource, Acl::ACTION_DELETE);
                Signatures::model()->loadModel($id)->delete();
                if (!isset($_GET['ajax']))
                        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }
        
        public function actionActivate($id , $st = FALSE)
    {
        $this->hasPrivilege(Acl::ACTION_UPDATE);
         $model = Signatures::model()->loadModel($id);
        $model->Status = $st == FALSE ? Signatures::STATUS_INACTIVE : Signatures::STATUS_ACTIVE;
              $model->save(FALSE);

                if (!isset($_GET['ajax']))
                        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('sms'));
                 echo CHtml::script("$('#preloader').hide()");
    }

        public function actionRuntime()
        {
                $this->resource = UserResources::RES_SETTINGS_RUNTIME;
                $this->hasPrivilege(Acl::ACTION_VIEW);
                $this->pageTitle = Lang::t('System runtime logs');
                $this->activeMenu = self::MENU_SETTINGS_RUNTIME;
                $this->showPageTitle = TRUE;

                $log_file = '';
                if (isset($_POST['log_file'])) {
                        $log_file = $_POST['log_file'];
                }

                $base_path = Yii::getPathOfAlias('application.runtime') . DS;
                if (empty($log_file))
                        $log_file = $base_path . 'application.log';

                if (isset($_POST['clear'])) {
                        $this->hasPrivilege(Acl::ACTION_DELETE);
                        if (file_exists($log_file)) {
                                @unlink($log_file);
                        }
                }

                $log_files = Common::getDirectoryFiles($base_path . 'application.log*');

                $this->render('runtime', array(
                    'log_files' => $log_files,
                    'log_file' => $log_file,
                ));
        }

        public function actionSignatures()
        {
                $this->resource = UserResources::RES_SETTINGS_SIGNATURES;
                $this->hasPrivilege(Acl::ACTION_VIEW);
                $this->showPageTitle = FALSE;
                $this->activeMenu = self::MENU_SETTINGS_SMS;
                $this->pageTitle = 'Sms ' . $this->resourceLabel;

                $model = new Signatures;
                $model_class_name = $model->getClassName();
                if (isset($_POST[$model_class_name])) {
                        $model->attributes = $_POST[$model_class_name];
                        if($model->save())
                        Yii::app()->user->setFlash('success', Lang::t('SUCCESS_MESSAGE'));
                        $this->refresh();
                }
                
                
                $this->render('sms', array(
                    'model' => $model,
                ));
        }
        public function actionSms()
        {
                $this->hasPrivilege(Acl::ACTION_VIEW);
                $this->resourceLabel = "Notification template";
                
                $this->pageTitle = Lang::t('Manage ' . $this->resourceLabel);

                $this->render('sms', array(
                    'model' => SettingsSmsTemplate::model()->searchModel(array(), $this->settings[Constants::KEY_PAGINATION],
                            'id' ,"sms_type = '". SettingsSmsTemplate::SMS_NOTIFY."'"),
                ));
        }

}

app/modules/customization/controllers/SmsController.php
<?php

class SmsController extends SettingsModuleController {

        public function init()
        {
                $this->resource = UserResources::RES_SEND_EMAIL;
                $this->resourceLabel = 'Sms Module';
                $this->activeMenu = self::MENU_SETTINGS_EMAIL;

                parent::init();
        }

        /**
         * @return array action filters
         */
        public function filters()
        {
                return array(
                    'accessControl', // perform access control for CRUD operations
                    'postOnly + delete', // we only allow deletion via POST request
                );
        }

        /**
         * Specifies the access control rules.
         * This method is used by the 'accessControl' filter.
         * @return array access control rules
         */
        public function accessRules()
        {
                return array(
                    array('allow',
                        'actions' => array('index', 'view', 'create', 'delete'),
                        'users' => array('@'),
                    ),
                    array('deny', // deny all users
                        'users' => array('*'),
                    ),
                );
        }

        /**
         * Displays a particular model.
         * @param integer $id the ID of the model to be displayed
         */
        public function actionView($id)
        {
                //@todo
                $this->redirect(array('create'));
        }

        /**
         * Creates a new model.
         * If creation is successful, the browser will be redirected to the 'view' page.
         */
        public function actionCreate()
        {
                $this->hasPrivilege(Acl::ACTION_CREATE);

                $this->pageTitle = 'Send' . ' ' . $this->resourceLabel;

                $model = new EmailQueue(EmailQueue::SCENARIO_MASS_EMAIL);
                $model->sent_by = Yii::app()->user->id;
                $model->from_name = Yii::app()->settings->get(Constants::CATEGORY_GENERAL, Constants::KEY_COMPANY_NAME, 'xchnge');
                $model->from_email = Yii::app()->settings->get(Constants::CATEGORY_GENERAL, Constants::KEY_ADMIN_EMAIL, 'support@xchnge.co');
                $model_class_name = $model->getClassName();

                if (isset($_POST[$model_class_name])) {
                        $model->attributes = $_POST[$model_class_name];

                        if ($model->validate()) {
                                Yii::app()->user->setFlash('success', Lang::t('Email successfully queued for sending.'));
                                $this->refresh();
                        }
                }

                $this->render('create', array(
                    'model' => $model,
                ));
        }

        /**
         * Deletes a particular model.
         * If deletion is successful, the browser will be redirected to the 'admin' page.
         * @param integer $id the ID of the model to be deleted
         */
        public function actionDelete($id)
        {
                $this->hasPrivilege(Acl::ACTION_DELETE);
                EmailQueue::model()->loadModel($id)->delete();
                if (!isset($_GET['ajax']))
                        $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
        }

        public function actionIndex()
        {
                //@todo
                $this->redirect(array('create'));
        }

}

app/modules/customization/views/sms/_form.php
<?php
$form_id = 'email-queue-form';
$form = $this->beginWidget('CActiveForm', array(
    'id' => $form_id,
    'enableAjaxValidation' => false,
    'htmlOptions' => array('class' => 'uk-form uk-form-horizontal uk-panel uk-panel-box')
        ));
?>
<?php echo $form->errorSummary($model, ''); ?>
<div class="uk-form-row">
        <?php echo $form->labelEx($model, 'from_email', array('class' => 'uk-form-label', 'label' => 'From Email:')); ?>
        <div class="uk-form-controls">
                <?php echo $form->textField($model, 'from_email', array('class' => 'uk-form-width-large', 'maxlength' => 128)); ?>
        </div>
</div>
<div class="uk-form-row">
        <?php echo $form->labelEx($model, 'from_name', array('class' => 'uk-form-label', 'label' => 'From Name:')); ?>
        <div class="uk-form-controls">
                <?php echo $form->textField($model, 'from_name', array('class' => 'uk-form-width-large', 'maxlength' => 60)); ?>
        </div>
</div>
<div class="uk-form-row">
        <?php echo $form->labelEx($model, 'subject', array('class' => 'uk-form-label', 'label' => 'Subject:')); ?>
        <div class="uk-form-controls">
                <?php echo $form->textField($model, 'subject', array('class' => 'uk-form-width-large', 'maxlength' => 255)); ?>
        </div>
</div>
<div class="uk-form-row">
        <?php echo $form->labelEx($model, 'message', array('class' => 'uk-form-label', 'label' => 'Message:')); ?>
        <div class="uk-form-controls">
                <?php echo $form->textArea($model, 'message', array('class' => 'uk-form-width-large redactor', 'rows' => 6)); ?>
        </div>
</div>
<div class="uk-form-row">
        <?php echo $form->labelEx($model, 'send_type', array('class' => 'uk-form-label', 'label' => 'Type:')); ?>
        <div class="uk-form-controls">
                <?php echo $form->dropDownList($model, 'send_type', $model->sendTypeOptions(), array('class' => 'uk-form-width-medium')); ?>
        </div>
</div>
<hr/>
<div class="uk-form-row">
        <div class="uk-form-controls">
                <button class="uk-button uk-button-primary" type="submit"><?php echo Lang::t('Send Now') ?></button>
                <a class="uk-button" href="<?php echo $this->createUrl('default/index') ?>">Cancel</a>
        </div>
</div>
<?php $this->endWidget(); ?>
<?php
Yii::import('ext.redactor.ImperaviRedactorWidget');
$this->widget('ImperaviRedactorWidget', array(
    // the textarea selector
    'selector' => '.redactor',
    // some options, see http://imperavi.com/redactor/docs/
    'options' => array(
        'minHeight' => 150,
        'convertDivs' => false,
        'cleanup' => TRUE,
        'paragraphy' => false,
    ),
    'plugins' => array(
        'fullscreen' => array(
            'js' => array('fullscreen.js',),
        ),
    ),
));
?>

app/modules/customization/views/sms/create.php
<div class="uk-grid">
        <div class="uk-width-medium-2-5">
                <article class="uk-article">
                        <h3 class="uk-article-title"><?php echo CHtml::encode($this->pageTitle) ?></h3>
                </article>
        </div>
        <div class="uk-width-medium-3-5">
                <div class="uk-button-group uk-float-right">
                        <a class="uk-button" href="<?php echo $this->createUrl('default/index') ?>">Cancel</a>
                </div>
        </div>
</div>
<hr class="uk-article-divider">
<?php $this->renderPartial('/widgets/_alert') ?>
<?php $this->renderPartial('_form', array('model' => $model)); ?>